version: '3.8'
services:
  node:
    restart: unless-stopped
    build: .
    ports:
      - 8000:8000
    #volumes:
      #- ./:/app
    networks:
      - webinar_default
networks:
  webinar_default:
    #driver: bridge
    external: true
